---
abstract: 'Catmandu tools for working with markdown data'
author:
  - 'Nicolas Franck C<< <nicolas.franck at ugent.be> >>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Markdown
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: 0.9
  Text::Markdown::Discount: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Markdown/issues
  homepage: https://github.com/LibreCat/Catmandu-Markdown
  repository: https://github.com/LibreCat/Catmandu-Markdown.git
version: 0.011
